language: ruby
rvm:
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rspec spec
