language: ruby
rvm:
  - 2.2.0
  - 2.1.5
  - 2.1.4
  - 2.1.3
  - 2.1.2
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rspec spec
