require 'vcr'
require 'capybara'
require 'site_prism'
require 'webmock'

require 'site_prism_vcr/version'
require 'site_prism_vcr/element'
require 'site_prism_vcr/element_container'
require 'site_prism_vcr/fixtures'
require 'site_prism_vcr/fixtures_handler'
require 'site_prism_vcr/fixtures_adjuster'